version: '3.8'

services:
  web:
    image: custom-nginx
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - nginx_certs:/etc/nginx/ssl
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: unless-stopped
    networks:
      - inception-network
    healthcheck:
      test: [ "CMD", "curl", "-k", "http://localhost:443" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  wordpress:
    image: custom-wordpress
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - .env
      #ENV_FILE: "1"
    restart: unless-stopped
    networks:
      - inception-network
    healthcheck:
      test: [ "CMD", "nc", "-z", "wordpress", "9000" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    depends_on:
      - mariadb
  mariadb:
    image: custom-mariadb
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      - .env
    networks:
      - inception-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

networks:
  inception-network:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mukibrok/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mukibrok/data/mariadb
